### ISSUE TITLE
Support ``Union``

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#114]
## Issue with ``Union`` type in type-hint-based dependency injection.
Making type alias with ``Union`` can cause unexpected side-effect or type hinting conflict of providers so it was not supported yet.
For example, if you have same type variables in the ``Union``, the alias are considered to be ``equal``(==) regardless of the order of type variables.
But it's not the same instance if the order of type variables are not the same.

Here are some examples of equality check and instance check:
```python
from typing import Union, NewType
alias_a = Union[int, str]
alias_b = Union[str, int]

alias_a is Union[int, str]  # True
alias_a is Union[str, int]  # False

alias_a == alias_b  # True
alias_a is alias_b  # False
alias_a == Union[int, str]  # True
```
## Suggestion
This conflict can be avoided if you first define ``NewType``s of each type variable you want to combine.
For example, 
```python
from typing import Union, NewType

AInt = NewType("AInt", int)
BInt = NewType("BInt", int)
AStr = NewType("AStr", str)
BStr = NewType("BStr", str)

alias_a = Union[_AInt, AStr] 
alias_b = Union[_BInt, BStr]
```

This way, it is much less likely to use ``Union`` with the same type accidentally with a few more lines.

### ``int`` or ``str``
Integer index or string index is often converted to the other type.
So there might be providers that want to accept both and handle the type itself.

### ``Path`` or ``str``
It is convenient if a file loader can accept both ``pathlib.Path`` and ``str`` type for a file path.

We can write a loader like below:
```python
import pathlib
from typing import Union, NewType

FilepathPath = NewType("FilepathPath", pathlib.Path)
FilepathStr = NewType("FilepathStr", str)
InputFilepath = Union[FilepathPath, FilepathStr]

def file_loader(file_path: InputFilepath) -> list[int]:
    ...  # Read file and return the result
```

**Comment by SimonHeybrock** [comment]
This does not seem related to what Beamlime is supposed to do. Is this necessary and relevant?

**Comment by YooSunYoung** [comment]
> This does not seem related to what Beamlime is supposed to do.  Is this necessary and relevant?
True... it is more related to workflows.
Do you think this idea is valid for sciline as well?

But beamlime also has a dependency injection helper and it will eventually need to deal with user interfaces
so I thought it was more worth mentioning here as well.

**Comment by SimonHeybrock** [comment]
I don't think we should spend much time on developing a dependency injection framework as part of Beamline.

**Comment by YooSunYoung** [comment]
> I don't think we should spend much time on developing a dependency injection framework as part of Beamline.

I agree. We can come back to this again only if it takes too much time to deal with multiple-types of inputs later.

**Comment by SimonHeybrock** [comment]
> > This does not seem related to what Beamlime is supposed to do.  Is this necessary and relevant?
> 
> True... it is more related to workflows. Do you think this idea is valid for sciline as well?

Workflows will not use Beamlime's DI framework. Sciline now supports `Union` requirements btw.

> But beamlime also has a dependency injection helper and it will eventually need to deal with user interfaces so I thought it was more worth mentioning here as well.

I will then close this, until we have prove that it is required, so we can keep the issue list lean.
