### ISSUE TITLE
Define workflow interface

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/beamlime#131]
Ideas from preliminary discussion:

```python
class MyWorkflow(beamlime.Workflow):
    def __init__(self, run_start, params: dict[str, ParamValue]):
        self.pipeline = sciline.Pipeline()

    # Later, do not include in v1?
    def get_params(self) -> dict[str, ParamSpec]:
        """Return parameters for the workflow that can be configured by a user."""
        return {'wavelength-binning': ParamSpec(float, 0.0, 10.0, description='Wavelength binning', default=0.1)}

    def __call__(self, merged_chunk) -> sc.DataGroup:
        """
        Return plottable data
        
        For now return merged data. If workflow wants merge, it has to do it itself.
        We can later extract this, since it is somewhat generic (or implement helpers
        in this base class). Options are:
        - Show average over last X seconds.
        - Show total since start.
        """ 
        self.pipeline[RawData[SampleRun]] = merged_chunk
        return self.pipeline.compute(IofQ[SampleRun])
```

 - We might want to make this a `Protocol` so it can be implemented in packages that do not depend on Beamlime.
 - See #134, should this be done before calling the workflow? Should `Workflow` define an interface for customizing this? What if the workflow wants to perform additional setup steps based on static input that it wants to avoid reperforming?
 - Consider the problem of finding the correct merge-mode in #135. Should the workflow interface require from the workflow inplementer to specify this?

**Comment by jokasimr** [comment]
Here's a small example workflow as food for discussion. It requires the implementer to do a lot of manual work, merging the numerators and denominators etc. But it is intended to handle things like moving detector banks or environment changes.

I excluded the `process_chunk` method here because I felt it wasn't really sure how it should handle changes in the environment.

```python
def apply_workflow_to_stream_of_chunks(
    workflow_cls, stream: Iterator[Chunk]                 
) -> Iterator[Result]:     
    
    # Read run_start message
    workflow = workflow_cls(next(stream))
    for chunk in stream:
        workflow.merge(chunk)
        yield workflow.produce_result()


class SANSWorkflow:
    def __init__(self, run_start):
        self.pipeline = ...
        self.num = DataArray(zeros, coords=...)
        self.den = DataArray(zeros, coords=...)
    
    def merge(self, chunk: Chunk):
        if chunk.message == 'detector_moved':
            self.pipeline[DetectorGeometry] = chunk['detector']['geometry']
            self.pipeline[SolidAngle] = state.pipeline.compute(SolidAngle)

        if chunk.message == 'detector_mask':
            self.pipeline[DetectorMask] = chunk['detector']['mask']

        if chunk.message == 'sample_event_data':  
            state.pipeline[RawData] = chunk
            num, den = pipeline.compute((CleanNumerator[Sample], CleanDenominator[Sample]))
            self.num += num
            self.den += den

    def produce_result(self):                              
        self.pipeline[CleanNumerator[Sample]] = state.num
        self.pipeline[CleanDenominator[Sample]] = state.den
        return self.pipeline.compute(IofQ[Sample])
```

**Comment by SimonHeybrock** [comment]
Ok, so you are talking about a different kind of merge, not the one *after* processing chunks. It actually looks like what `process_chunk` might do.

**Comment by SimonHeybrock** [comment]
Moving this out of the "Baseline" milestone, will proceed as described in #145 instead, as more data is needed here. I have put it into the follow-up milestone for now, but this may be pushed further, depending on the outcomes of #145.

**Comment by SimonHeybrock** [comment]
Slightly different idea:
- Always pass full data (merge of run-start and update chunk) to workflow.
- Write workflow in a way that it only reads chunks of events (and logs).

Advantages:
- Simple and flexible workflow interface. Workflow can "do as it pleases".
- Beamlime does not have to worry, e.g., about ensuring that every update has at least one value per log (even if not in update), etc., instead the workflow can just read the last N (or all log values), depending on its requirements.
- Maybe more aligned with chunking support for file-based workflows?

**Comment by jokasimr** [comment]
I'm not directly against it, things that makes things simpler are well worth considering. However, if I understood you correctly, there's one rather important disadvantage:

* Always passing the full data means we need to have the full data in memory, even if the workflow implements a smart reduction algorithm that can reduce the data chunkwise.

**Comment by SimonHeybrock** [comment]
Not the full data, just the full run-start message.

**Comment by jokasimr** [comment]
Aha I see what you mean now. That sounds reasonable. Is there a risk the run-start message is large?

**Comment by SimonHeybrock** [comment]
There is (e.g., from large DREAM geometry), but we will worry about that later.

**Comment by jokasimr** [comment]
I might be a bit out of the loop here, but what does
> Beamlime does not have to worry, e.g., about ensuring that every update has at least one value per log (even if not in update), etc., instead the workflow can just read the last N (or all log values), depending on its requirements.
mean?

* Is it possible we receive updates with no values?
* If we do, why does beamlime have to care?

**Comment by jokasimr** [comment]
> or the workflow would have to do that.

I think that's the easiest solution,  making the workflows responsible for merging their data chunks.
That means that if there was no new temperature value in the last chunk the workflow would have to know that it should use the temperature value from an earlier chunk, or the mean of the last five values, or something different depending on the needs of that workflow.

It seems complicated to make assumptions about what that merge process looks like in beamlime.

**Comment by SimonHeybrock** [comment]
> I think that's the easiest solution, making the workflows responsible for merging their data chunks.

Why do you think this is easiest? We will have 20+ different workflows, and in principle allow customization by scientists. The entry-barrier to writing (or at least modifying) workflows must be low. We should implement the difficult things once, not push them into the workflows.

> That means that if there was no new temperature value in the last chunk the workflow would have to know that it should use the temperature value from an earlier chunk, or the mean of the last five values, or something different depending on the needs of that workflow.

This contradicts your first sentence? But indeed the workflow should not have to know. It should either get all or the most recent value(s) of an NXlog. The alternative is having workflows with a lot of state, representing all the NXlogs in a "file", and logic that iterates all NXlogs in an update chunk, updating the NXlogs in the state and deciding correctly which part of the workflow needs to be recomputed. I do not feel that is feasible.

**Comment by jokasimr** [comment]
Okay first of all you know much more about the different cases we are going to encounter, the different techniques, the different instruments and their modes etc. So you also have a better view of what we're going to need. That said, here's why I think it seems easier to not merge/concatenate data before passing it to the workflow:

* Chunking some streams (logs) and not others (events) makes the interface more complicated to understand and to explain (to the scientist modifying the workflow). This is not an issue if we manage it well.
* What about long running experiments? Might the total memory used by all NXlogs become significant? If we store the concatenation of all logs in beamlime that would be difficult to deal with from within the workflow.

I'm all for implementing the difficult things once. If 10 workflows just concatenates the logs, we can implement that logic in essreduce and reuse it in those workflows while still having the flexibility to do something different elsewhere.

> This contradicts your first sentence?

I don't understand what you're referring to. It seems there is some misunderstanding here.

**Comment by SimonHeybrock** [comment]
> What about long running experiments? Might the total memory used by all NXlogs become significant? If we store the concatenation of all logs in beamlime that would be difficult to deal with from within the workflow.

We probably will not. Maybe just the last value, and the current update, or something. But for now we can keep it simple and keep everything.

Everything you say above is, for me, a reason to handle it "centrally" and *not* in the workflow, because otherwise implementing workflows will become very challenging.

But my recommendation is to start simple (thus the stateless workflow interface) and then iterate, once we have *data* to inform our decision of what works and what does not, and where the bottlenecks are.
