### ISSUE TITLE
Workflow plugin architecture

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/beamlime#132]
- Make workflows loadable as plugins.
- See https://github.com/ArjanCodes/2021-plugin-architecture for an example.

**Comment by YooSunYoung** [comment]
More references:

https://flask.palletsprojects.com/en/3.0.x/blueprints/

But instead of importing a class like `Blueprint`,
we can define a Protocol so that the plugins don't necessarily have to be dependent on ``beamlime``.

**Comment by jl-wynen** [comment]
Have a look at https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins for a way to register plugins using entry points.

**Comment by SimonHeybrock** [comment]
Loaded plugins should be used somewhere here: https://github.com/scipp/beamlime/blob/d2bc0b6d0593ac6ec28310006c5dc1b1e20f5752/src/beamlime/stateless_workflow.py#L36-L38
