### ISSUE TITLE
Create fake that produces messages equivalent to Kafka listener

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/beamlime#139]
Tasks such as #133 and #138 operate on the JSON we get from Kafka. For development and testing it would be essential to have a fake that produces such messages. Possible approach:

- Stream a real file (such as from ESSsans/Loki).
- Record and save the JSON to file(s).
- Add fake that "produces" these messages by loading from the files.
- For time-dependent content we can limit ourselves to a few messages, for now at least. Large data is not required.

An alternative would be to directly implement a NeXus -> JSON converter, but I think I do not like that since we then build our software stack on assumptions/mistakes we made when writing that converter. Better use the actual streamed data!

**Comment by YooSunYoung** [comment]
> Stream a real file (such as from ESSsans/Loki).

How should we stream a file though...? By [nexus-streamer-python](https://github.com/ess-dmsc/nexus-streamer-python)...?

> An alternative would be to directly implement a NeXus -> JSON converter, but I think I do not like that since we then build our software stack on assumptions/mistakes we made when writing that converter. Better use the actual streamed data!

We could probably just use [nexus -> JSON converter](https://github.com/ess-dmsc/nexus-streamer-python/blob/main/src/nexus_streamer/generate_json_description.py) in [nexus-streamer-python](https://github.com/ess-dmsc/nexus-streamer-python) but they don't have any tests for this method...

**Comment by YooSunYoung** [comment]
@SimonHeybrock  I'll leave the answer to the chat here!

> Does Beamlime (one of the prototypes, maybe?) already include something that provides a JSON Nexus, as we would get it 
from Kafka (but without running Kafka)?

One of the prototypes was producing messages itself from a dummy data so...
it should be possible to just skip the communication with the kafka and just use them directly...?

**Comment by SimonHeybrock** [comment]
How close is the dummy data to the JSON we get from Kafka? How did you make it?

**Comment by YooSunYoung** [comment]
> How close is the dummy data to the JSON we get from Kafka? How did you make it?

For producing event data, it uses the schema Daniel mentioned in the chat,
so the whole structure should be exactly same at least.
This one for event data: https://github.com/ess-dmsc/streaming-data-types/blob/master/schemas/ev44_events.fbs
I'm not sure what they put as a `source_name` for example.

But it doesn't have any log data producing part.

**Comment by SimonHeybrock** [comment]
I think we can assume that our Kafka listener will know how each `ev44` and [f144](https://github.com/ess-dmsc/streaming-data-types/blob/master/schemas/f144_logdata.fbs) will map to an NXevent_data and NXlog, respectively. Therefore:

1. We have some run-start messages (see Slack).
2. We can make some fake log values and events, to produce "update" messages.

**Comment by SimonHeybrock** [comment]
Add a fake that can take the place of a real listener and produces messages as they would have been obtained from Kafka.

- Add `class FakeListener` (similar to the current `StreamSimulator`?), see #152.
- Afterwards this will produce "update" messages, containing event data and log data, see #153.
- Logs [f144](https://github.com/ess-dmsc/streaming-data-types/blob/master/schemas/f144_logdata.fbs) and [tdct](https://github.com/ess-dmsc/streaming-data-types/blob/master/schemas/tdct_timestamps.fbs) (for choppers) should be handled later.

**Comment by YooSunYoung** [comment]
Ah...! I thought they were deleted in the ``options.py``...! I'll clean them up sorry...!

**Comment by YooSunYoung** [comment]
Done by #165 and #156
