### ISSUE TITLE
Update minimum python version

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#15]
We're currently using `pyhton3.8` for minimum version but as soon as we don't need to use `Mantid`, we can upgrade it to `python3.9`

**Comment by jl-wynen** [comment]
Note that this applies to the whole Scipp ecosystem. And we will rather update on the next release of Mantid which should update to Python 3.10.

**Comment by SimonHeybrock** [comment]
Imho you can update this project now. By the time someone needs this and Mantid in the same environment it will have 3.9 support.

**Comment by YooSunYoung** [comment]
Using python3.9 as minimum.
