### ISSUE TITLE
Add `FakeListener`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/beamlime#152]
Add a fake that can take the place of a real listener and produces messages as they would have been obtained from Kafka. This is part of #139.

- Add `class FakeListener` (similar to the current `StreamSimulator`?)
- Can be initialized from a JSON run-start message, as found in https://gitlab.esss.lu.se/ecdc/nexus-json-templates.
- Will send a single message to the message router, containing the run-start message *with empty NXevent_data and NXlog* groups.
- Messages with event data and log data will be added in follow-up tasks.

**Comment by jokasimr** [comment]
What is a ` JSON run-start message`? Are all the templates in https://gitlab.esss.lu.se/ecdc/nexus-json-templates run start messages?

**Comment by jokasimr** [comment]
Is the message that is sent to the message router supposed to be a scipp `DataGroup`?

**Comment by YooSunYoung** [comment]
> Is the message that is sent to the message router supposed to be a scipp `DataGroup`?

No, it should follow the ``MessageProtocol``
https://github.com/scipp/beamlime/blob/8958ea820d994e60941c56cd178797443f3db507/src/beamlime/applications/base.py#L82-L86

And the ``content`` may be annotated somewhere else, for the KafkaListener's case,
since the ``content`` is expected to be handled by ``DataReductionHandler.process_message``,
and be fed to the ``StatelessWorkflow`` instance,
https://github.com/scipp/beamlime/blob/8958ea820d994e60941c56cd178797443f3db507/src/beamlime/applications/handlers.py#L42-L47

It should be ``JSONGroup`` according to the ``StatelessWorkflow`` protocol.

https://github.com/scipp/beamlime/blob/8958ea820d994e60941c56cd178797443f3db507/src/beamlime/stateless_workflow.py#L15-L17

**Comment by YooSunYoung** [comment]
> What is a ` JSON run-start message`? Are all the templates in https://gitlab.esss.lu.se/ecdc/nexus-json-templates run start messages?

I think it just means a dictionary that looks like this...? [pl72_run_start.fbs](https://github.com/ess-dmsc/streaming-data-types/blob/7e80bde7c64f13235ac21f8da9ae86bb40cc2c97/schemas/pl72_run_start.fbs#L14-L31)
```
table RunStart {                                     //  *Mantid*    // *File Writer* // *Description*
    start_time : uint64;                             //  Required    //  Required     // milliseconds since Unix epoch (1 Jan 1970)
    stop_time : uint64;                              //  Unused      //  Optional     // milliseconds since Unix epoch (1 Jan 1970), optional, can send a RunStop instead
    run_name : string;                               //  Required    //  Unused       // Name for the run, used as workspace name by Mantid
    instrument_name : string;                        //  Required    //  Unused       // Name of the instrument, only required by Mantid
    nexus_structure : string;                        //  Optional    //  Required     // JSON description of NeXus file (See https://github.com/ess-dmsc/kafka-to-nexus/ for detail)
                                                                                      // If present Mantid will parse this to get the instrument geometry, otherwise it will attempt
                                                                                      // to look up an Instrument Definition File (IDF) based on the instrument name
    job_id : string;                                 //  Unused      //  Required     // Uuid for the file writing job, serves as job-id.
    broker : string;                                 //  Unused      //  Unused       // (Obsolete) Broker name and port, for example "localhost:9092", from which the file writer should get data
    service_id : string;                             //  Unused      //  Optional     // The identifier for the instance of the file-writer that should handle this command
    filename : string;                               //  Unused      //  Required     // Name of the file to write, for example run_1234.nxs
    n_periods : uint32 = 1;                          //  Optional    //  Unused       // Number of periods (ISIS only)
                                                                                      // Periods provide a way to segregate data at the data acquisition stage
    detector_spectrum_map: SpectraDetectorMapping;   //  Optional    //  Unused       // Map spectrum numbers in the event messages to detector IDs in the instrument definition (optional, for ISIS only)
    metadata : string;                               //  Unused      //  Optional     // Holds a JSON string with (static) metadata about the measurement. E.g. proposal id.
    control_topic : string;                          //  Unused      //  Optional     // Topic on which the File Writer will listen for further commands and publish status messages when started from a pool
}
```

**Comment by SimonHeybrock** [comment]
Yes, I was unclear. What the `FakeListener` will return is actually the `nexus_structure` of the `pl72` that @YooSunYoung  posted. The fake listener will never actually have a run-start message, it would simply return a `nexus_structure`, such as https://gitlab.esss.lu.se/ecdc/nexus-json-templates/-/blob/main/loki/loki.json?ref_type=heads.

In the next milestone after this, we will likely want to add an "earlier" fake. This is, instead of having

```mermaid
graph LR;
  FakeListerer-->Reduction;
```
we will have
```mermaid
graph LR;
  FakeKafka-->KafkaListener-->Reduction;
```
Where `FakeKafka` will pass a run-start message to the `KafkaListener`, which then extracts, e.g., the `nexus_structure` and forwards it to the `Reduction`.

**Comment by jokasimr** [comment]
It seems like `JSONGroup` [isn't part of the public api](https://scipp.github.io/scippneutron/search.html?q=JSONGroup) of `scippneutron`. Should it be? Why is that type used for the argument in `StatelessWorkflow`?

**Comment by SimonHeybrock** [comment]
> It seems like `JSONGroup` [isn't part of the public api](https://scipp.github.io/scippneutron/search.html?q=JSONGroup) of `scippneutron`. Should it be? Why is that type used for the argument in `StatelessWorkflow`?

I will/should be made public. It is internal due to history: Before ScippNexus existed, all that code was in ScippNeutron, so JSONGroup was never made public.
