### ISSUE TITLE
Add generator of fake events for `FakeListener`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/beamlime#153]
Part of #139, follow-up to #152.

- Generate fake events in the `FakeListener`.
  - This may include events for multiple banks, if present in the run-start message (used for initializing the `FakeListener`).
  - `pixel_id` must be setup correctly for the pixel IDs of each bank.
  - Generate random noise, no special shape or distribution for now.
- Produce messages to Beamlimes message router with updates, e.g., once every N seconds.
  - Use #134 to merge the static data with the fake event data.
- We assume the original messages from Kafka have been concatenated within the listener over a period of time. The updates should thus contain a nested json (structure given my the run-start message) containing updates from multiple ev44 (later this will also include f144 / tdct, do not add this for now) Kafka messages.
- The event data should be based on [ev44](https://github.com/ess-dmsc/streaming-data-types/blob/master/schemas/ev44_events.fbs), excluding the `source_name` (which gives the location in the json) and the `message_id` (which is something the listener would handle internally, but not forward to the rest of Beamlime).

**Comment by YooSunYoung** [comment]
Fixed in #165
