### ISSUE TITLE
Handle ``f144(log)`` and ``tdct(chopper)``.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#171]
Currently ``DataReductionHandler`` can only insert ``ev44(event data)`` into the nexus structure.

But as mentioned in the #134, we also need to handle ``f144`` and ``tdct`` messages.

**Comment by jokasimr** [comment]
This was implemented in #134 but not tested.
So probably we only need to make sure that the current implementation works, or tweak it if it doesn't.
