### ISSUE TITLE
Async lock or threading lock needed for appending dataset.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#182]
For now, ``DataAssembler``, through ``NexusContainer``, create a shallow copy of the original nexus dictionary and update it. 
Therefore, it is not guaranteed that ``NexusContainer.nexus_dict`` is always the latest one.

For example, if there is an unnecessary ``asyncio.sleep`` in the middle of handling method like below,
```python
nexus_dict = {'event' = []}
nexus_container = {'nexus_dict': nexus_dict}

async def handling_method() -> None:
  copied = nested_shallow_copy(nexus_container['nexus_dict'])
  copied['event'].append(3)
  await asyncio.sleep(0)
  nexus_container['nexus_dict'] = copied

await handling_method()
await handling_method()
   
```
The expected result of ``nexus_container`` should be
```python
{
  'nexus_dict': {'event': [3, 3]}
}
```
But it might be 
```python
{
  'nexus_dict': {'event': [3]}
}
```
Because of the ``asyncio.sleep`` in the middle, because the latest result was not updated in the ``nexus_container``.

So this should be handled when we want to append data in the ``nexus_container``.
It may be handled by async ``Lock``.

**Comment by jl-wynen** [comment]
In this example, it is a bit strange that you copy the dict and then insert the copy back into the outer dict. Instead, it seems more reasonable to have an atomic operation on the nested dict and modify it in place along the lines of

```python
async def handling_method() -> None:
  new_value = some_function_that_maybe_uses_nexus_container()
  await asyncio.sleep(0)
  atomic_append_event(nexus_container, new_value)

def atomic_append_event(container, value):
  # no lock needed in async context,
  # otherwise use thread mutex here
  container['nexus_dict']['event'].append(value
```

Does this also apply to the real code or is the example simplified too much?

**Comment by YooSunYoung** [comment]
>  Instead, it seems more reasonable to have an atomic operation on the nested dict and modify it in place along the lines of

You mean, we should make sure that the `old` one is used 
and then update it with new values in-place...?

**Comment by jl-wynen** [comment]
I don't understand what you mean. Let's have a quick call tomorrow!

**Comment by YooSunYoung** [comment]
This is not relevant anymore since we make sure we collect enough of the dataset first before we inject them into the whole structure.
