### ISSUE TITLE
Overall system design draft

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#2]

**Comment by SimonHeybrock** [comment]
Links to what Mantid does:
- https://archive.mantidproject.org/Live_Data_Monitoring.html
- https://docs.mantidproject.org/v4.0.0/tutorials/mantid_basic_course/live_data_analysis/03_live_data_user_interface.html

**Comment by YooSunYoung** [comment]
## Reference
https://archive.mantidproject.org/Live_Data_Monitoring.html

**Comment by YooSunYoung** [comment]
System design scribble

![Image](https://user-images.githubusercontent.com/17974113/220958780-57839473-97a2-4624-9d50-f5075860f2f9.jpg)

**Comment by YooSunYoung** [comment]
Got first feedback for this one.

![Image](https://user-images.githubusercontent.com/17974113/221897851-9ccc4c79-3d40-46c0-910f-e48c4f475934.png)



Things to update
- [ ] Splitting `preprocess` and `postprocess` in the workflow control module.
- [ ] Specify how we are going to share the information between the data reduction and the dashboard builder.

**Comment by YooSunYoung** [comment]
It will be updated in #51
