### ISSUE TITLE
Test FakeListener for fill-dummy-data option

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#243]
Now we are updating the beamlime to use nexus file to use static information including ``FakeListener`` starting with #242 .

Existing tests already cover a lot of the updated parts but we still need to add tests for ``fill-dummy-data`` option if it is actually retrieving data from the file if asked.

The ``ymir_detectors.nxs`` file does not have any event data, so we may want to make a temporary file and add event data, and then see if the result is as expected.

**Comment by SimonHeybrock** [comment]
It obviously works correctly, may not be worth adding a test that may require frequent refactoring.

**Comment by YooSunYoung** [comment]
Hmm yeah ... Maybe it's not so important since we already used it for manual testing a lot...
