### ISSUE TITLE
Logging and log parser/monitoring

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#34]
Currently applications just print to std I/O but they should be logged in the same place and collected.
Also, it should be easy to parse the log and for analysis.

We might also want performance monitoring, and logs should also have the related information. -> I am not quite sure if it should be separate thing or we can just use logs for this... it'll depend how and why we want to monitor the performance...?

Then we should also remove prompt coloring option from application constructors, mentioned here: #32

**Comment by SimonHeybrock** [comment]
Maybe Scipp's logging widget could be shown as one of the visualizations on the dashboard? See https://scipp.github.io/reference/logging.html.

**Comment by YooSunYoung** [comment]
> Maybe Scipp's logging widget could be shown as one of the visualizations on the dashboard? See https://scipp.github.io/reference/logging.html.

Yes I was thinking about it too.
