### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/beamlime#38]
We have the approximate boundary conditions outlined below. We should implement performance tests early on to ensure that the architecture is capable of handling this. The tests should be able to run at least semi-automatically, to ensure that they can easily be re-run with changes, to ensure we keep meeting the metrics.

- Event rates of up to 1e7 events/second. There may be instruments with more later (when the accelerator power is higher), but I think 1e7 is a good initial benchmark.
- Up to 10 million pixels. Typical is closer to 1 million.
- Updates of NXlog info from dozens or even more than 100 time-series logs. We can use an actual NeXus file as a baseline and then figure out how to model updates for all the NXlog groups.
- Live update of visualizations about once per second.

**Comment by SimonHeybrock** [comment]
Here is a notebook that can add a large number of events to our existing DREAM file (which will be an early offender in terms of high event rates):

[large-file.ipynb.zip](https://github.com/scipp/beamlime/files/11286267/large-file.ipynb.zip)

**Comment by SimonHeybrock** [comment]
I suggest as a first step before using actual neutron data we do something simpler:

- Some large NumPy arrays, initialized somehow.
- Should test sizes equivalent to the expected ranges, i.e., up to 1e7 (testing with 5e7 as a bonus) events/second -> 1e6 events per pulse, which would mean about 1e6*2*8 Byte = 16 MByte per pulse.
  - Time for concatenating a few pulses (1-10 seconds worth of pulses).
- Feed this data though the pipeline, with some operations to reduce it to 1-D.

**Comment by SimonHeybrock** [comment]
Here is some code for the simplest somewhat realistic test case, event data similar to what we get at some stage during loading/processing a chunk:

```python
import scipp as sc
from numpy.random import default_rng
rng = default_rng(seed=1234)


def make_event_data(*, npixel, nevent) -> sc.DataArray:
    weights = sc.ones(dims=['event'], shape=[nevent], unit='counts')
    pulse_time = sc.epoch(unit='ns') + sc.arange(
        'event', nevent, unit='ns', dtype='int64'
    )
    tof = sc.array(dims=['event'], values=rng.random((nevent,)), unit='s')
    pixel = sc.array(dims=['event'], values=rng.integers(npixel, size=(nevent,)), unit=None)
    da = sc.DataArray(weights, coords={'pulse_time': pulse_time, 'tof': tof, 'pixel':pixel})
    return da
```

Then we have to:

```python
npixel = int(1e5)  # interesting range: 1e4 to 1e7
nevent = int(1e6)  # interesting range: 1e4 to 1e7

chunk = make_event_data(npixel=npixel,nevent=nevent)
# possibly before or after merging chunks
da = chunk.group('pixel')
```

**Comment by YooSunYoung** [comment]
@SimonHeybrock pointed out that pixel ids would be split into multiple groups, 
i.e. 10M pixels into three groups, 2M, 2M and 6M. Depending on the detector they come from.

When we tried in a naive way, just splitting into 3, 5 groups evenly, the benchmark results are like below.

| Parameters | -------         | Benchmark Results [s] | ---------     | -------          |
|:---------------:|:--------------:|--------------------------------|--------------|----------------|
| event_rate | num_pixels | without splitting groups | 3 groups | 5 groups     |
| 1e7             | 1e7             | 41                                 | 18            | 13              |
| 1e8             | 1e7             | 191                               | 224          |  184           |

**Comment by SimonHeybrock** [comment]
Interesting. Why does the amount of RAM make such a difference? Is the hardware identical otherwise? Does it get even better with 256 GByte?

**Comment by YooSunYoung** [comment]
> Interesting. Why does the amount of RAM make such a difference? Is the hardware identical otherwise? Does it get even better with 256 GByte?
Yeah... it's not really a fair comparison since the 128 GB one had more cores...
I asked Brian for a 256 GB VISA instance with same number of cores as 64 GB one. We'll see...!

**Comment by SimonHeybrock** [comment]
Can you include all the relevant hardware stats (such as processor) in the figures?

**Comment by YooSunYoung** [comment]
Sorry it took a while to collect them again...!
Here are performance contour plots and relative performance plots with different RAM or number of cpu cores(physical).

# Performance contour plot
(On VISA, 128GB RAM, 6 cores)
![beamlime-performance-contour-plot](https://github.com/scipp/beamlime/assets/17974113/fb19773e-c13e-45be-b3bc-799f991de08b)

# Parameter: RAM
## Performance contour plot with different RAM capacities.
![beamlime-performance-contour-plot-ram](https://github.com/scipp/beamlime/assets/17974113/aae2d8be-9477-4e52-8eda-7c176b5b0b26)

## Relative performance of different RAM capacities
![beamlime-performance-differences](https://github.com/scipp/beamlime/assets/17974113/38319b58-14bc-4d87-aff2-4312c9b43be7)

# Parameter: Number of CPU cores
## Performance contour plot with different number of cores.
![beamlime-performance-contour-plot-cores](https://github.com/scipp/beamlime/assets/17974113/4c60f2b6-92fc-41e5-890a-1b0502fcf30c)

## Relative performence of different number of cores
![beamlime-performance-differences-cores](https://github.com/scipp/beamlime/assets/17974113/6fdaa309-850b-408f-b166-e53cb76cee74)

# Conclusion
I couldn't see meaningful correlation between memory capacity and process speed.
Number of CPU cores affects significantly for large number of event data or large number of pixel ids as expected.

**Comment by SimonHeybrock** [comment]
> Relative performance of different number of cores

So you report a 200% speedup (i.e., 3x the speed) for doubling the number of cores? Any idea why it is not 100% have you tried other numbers of cores? How about 24? How does the scaling continue?

**Comment by YooSunYoung** [comment]
> So you report a 200% speedup (i.e., 3x the speed) for doubling the number of cores? Any idea why it is not 100%? Have you tried other numbers of cores? How about 24? How does the scaling continue?

Sorry it was mislabeled...! One of them has 24 cores. I had to manually label it since I couldn't automatically retrieve it into the report on VISA for some reason... I just updated the plot.

But I don't have 12 cores option at the moment.

**Comment by SimonHeybrock** [comment]
Then 3x makes sense 👍

**Comment by YooSunYoung** [comment]
Here is the performance overhead plot:

![output](https://github.com/scipp/beamlime/assets/17974113/e5ca68a7-ecc8-4def-bf33-e516041a0ea4)

**Comment by SimonHeybrock** [comment]
Should we call this done?
