### ISSUE TITLE
Check Cyclic dependency earlier

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#69]
Currently, dependency injection core catches `RecurssionError` when there is a cyclic dependency.
It should be detected earlier and have better explanation.

@jl-wynen suggested to use [a TologicalSorter method in graphlib](https://docs.python.org/3/library/graphlib.html?highlight=graphlib#graphlib.TopologicalSorter.prepare).

**Comment by SimonHeybrock** [comment]
As the DI framework needs to build a relatively small and static app, I think we can ignore this.
