### ISSUE TITLE
Cache clearing interface.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/beamlime#95]
`CachedProvider` allows to keep the first result of the function call and returns it from next call.

If it is called again, it checks if the arguments are the same as the first call otherwise raises an exception.

This is for keeping an obejct as a singleton within the single factory, so that any object doesn't have to be a singleton itself.

However, there is no interface for clearing cache.
One of the ways to clear cache is to copy the `CachedProvider`.
For example, we can simply copy all providers form the ``ProviderGroup`` and it will have no cache since it's a fresh new instance.
```python
from beamlime.constructor.providers import merge, ProivderGroup

def float_to_int(input_arg: float) -> int:
    return int(input_arg)

prov_gr = ProviderGroup()
prov_gr.cached_provider(float_to_int)
prov_gr[int](10.0)  # 10
prov_gr[int](9.0)  # raises

prov_gr = merge(prov_gr) # All providers are copied, so cache is also cleared.
prov_gr[int](9.0)  # 9
```
However, it unnecessarily copy all other providers so it might be better to have a dedicated cache clearing interface.
i.e.
```python
class CachedProvider:
    def clear_cache(self):
        # somehow clear cache
        ...

class ProviderGroup:
    def clear_cache(self):
        # filter cached providers and clear cache of each.
        ...

class Factory:
    def clear_cache(self):
        # call ``clear_cache`` interface of ``providers`` attribute.
        ...
```

**Comment by SimonHeybrock** [comment]
Is `CachedProvider` required for assembling the application? As Beamlime's DI framework should not interact with the data-reduction it might not. In any case (keeping `CachedProvider` or not), cache clearing seems irrelevant and this can be closed?

**Comment by YooSunYoung** [comment]
It was for sharing an instance across many instances.
But, if we choose to go with event driven as mentioned in #127 
this will not be needed any longer
since the singleton instance can ``clear`` itself based on the ``event``
